### ISSUE TITLE
Fatal error - daily scrobble cap

### ISSUE THREAD

**Issue by warthog3** [coczero/Last.fm-Scrubbler-WPF#82] opened 2019-07-28 03:46 UTC
Cannot scrobble when 2799 or 2800 tracks are checked. Have tried restarting application and reparsing iTunes library each time I've tried.

![scrobble capture](https://user-images.githubusercontent.com/4109409/62001892-83e37c80-b0af-11e9-93ab-8b7dfcb9437e.PNG)

**Comment by coczero** [comment] 2019-07-28 08:16
I'll look into it, thanks for reporting

**Comment by coczero** [comment] 2019-07-28 10:52
Ok, so the problem is that the "Num to scrobble" just shows the amount of tracks selected in the list, not counting the actual play counts (which are scrobbles when selecting a track).
So youre actually trying to scrobble way more than 2799 scrobbles.

**Comment by coczero** [comment] 2019-07-28 11:56
Fixed in https://github.com/coczero/Last.fm-Scrubbler-WPF/commit/7c146487d8fbc25f8ef51f549a861640b0d11a69

**Closed** 2019-08-06 17:06 UTC
Labels: bug, close on next release
