### ISSUE TITLE
App stops doing its job when minimized to the tray

### ISSUE THREAD

**Issue by asundersweet** [coczero/Last.fm-Scrubbler-WPF#43] opened 2018-06-06 17:44 UTC
This is an issue in the newest beta version. In iTunes scrobbling, whenever I minimize Scrubbler to the tray, the "scrobble-meter" stays at the position it was last in and the song ends up not being scrobbled. I have to reconnect to iTunes for the app to start scrobbling again, and when I minimize it the error persists.

**Comment by coczero** [comment] 2018-06-06 19:49
Thank you for reporting. I will investigate this.

**Comment by coczero** [comment] 2018-06-11 08:51
I have identified the cause of this error and am currently working on a solution.

**Comment by coczero** [comment] 2018-06-11 12:20
Fixed by https://github.com/coczero/Last.fm-Scrubbler-WPF/commit/0f1e3373746476995c38170db516f8754a8c081d

**Comment by asundersweet** [comment] 2018-06-12 13:17
Thank you for your work!

**Closed** 2018-07-30 22:02 UTC
Labels: accepted, bug, close on next release
